In [1]:
import os
import numpy as np
import pandas as pd

In [2]:
def get_df(results, cats, exemps):
    df = pd.DataFrame(index=exemps, columns=cats)
    for i, cat in enumerate(cats):
        for j, exe in enumerate(exemps):
            df[cat].loc[exe] = results[i,j]
    return df

# Note: axis 0 is categories, axis 1 exemplars

In [69]:
folder = '/Users/reubenfeinman/Desktop/cnn_results_secondOrder/'
results = np.load(os.path.join(folder, 'results.npy'))
category_trials = np.load(os.path.join(folder, 'category_trials.npy'))
exemplar_trials = np.load(os.path.join(folder, 'exemplar_trials.npy'))

In [51]:
print('categories: ', category_trials)
print('exemplars: ', exemplar_trials)

categories:  [10 15 20 25]
exemplars:  [ 5 10 15]


In [ ]:
# These are results for X_train definition inside the loop

In [45]:
results

array([[[ 0.5085,  0.3665,  0.352 ,  0.283 ,  0.529 ],
        [ 0.544 ,  0.558 ,  0.516 ,  0.7185,  0.628 ],
        [ 0.749 ,  0.64  ,  0.6315,  0.648 ,  0.6415]],

       [[ 0.516 ,  0.5355,  0.578 ,  0.525 ,  0.5885],
        [ 0.7705,  0.749 ,  0.7985,  0.846 ,  0.853 ],
        [ 0.7505,  0.812 ,  0.7215,  0.7765,  0.854 ]],

       [[ 0.539 ,  0.493 ,  0.3515,  0.5195,  0.3235],
        [ 0.8435,  0.7525,  0.819 ,  0.7945,  0.785 ],
        [ 0.8615,  0.893 ,  0.854 ,  0.8595,  0.8695]],

       [[ 0.512 ,  0.5285,  0.669 ,  0.3325,  0.658 ],
        [ 0.814 ,  0.805 ,  0.8365,  0.779 ,  0.814 ],
        [ 0.8955,  0.8585,  0.911 ,  0.858 ,  0.8585]]])

In [46]:
results.mean(axis=2)

array([[ 0.4078,  0.5929,  0.662 ],
       [ 0.5486,  0.8034,  0.7829],
       [ 0.4453,  0.7989,  0.8675],
       [ 0.54  ,  0.8097,  0.8763]])

In [ ]:
# These are results for X_train definition outside the loop (TBD)

In [70]:
results

array([[[ 0.3665,  0.3275,  0.2965,  0.3425,  0.3415],
        [ 0.6445,  0.64  ,  0.667 ,  0.445 ,  0.5395],
        [ 0.7165,  0.6525,  0.688 ,  0.7035,  0.71  ]],

       [[ 0.471 ,  0.474 ,  0.492 ,  0.5845,  0.6095],
        [ 0.771 ,  0.7975,  0.684 ,  0.857 ,  0.7585],
        [ 0.8105,  0.8375,  0.8115,  0.8425,  0.8345]],

       [[ 0.512 ,  0.5485,  0.399 ,  0.584 ,  0.408 ],
        [ 0.8245,  0.8125,  0.731 ,  0.7855,  0.781 ],
        [ 0.8875,  0.8925,  0.8605,  0.884 ,  0.906 ]],

       [[ 0.5255,  0.398 ,  0.57  ,  0.392 ,  0.3565],
        [ 0.762 ,  0.757 ,  0.8095,  0.8255,  0.8245],
        [ 0.896 ,  0.8885,  0.8855,  0.9145,  0.9085]]])

In [71]:
results.mean(axis=2)

array([[ 0.3349,  0.5872,  0.6941],
       [ 0.5262,  0.7736,  0.8273],
       [ 0.4903,  0.7869,  0.8861],
       [ 0.4484,  0.7957,  0.8986]])

In [72]:
folder = '/Users/reubenfeinman/Desktop/cnn_results_secondOrder/'
results = np.load(os.path.join(folder, 'results.npy'))
category_trials = np.load(os.path.join(folder, 'category_trials.npy'))
exemplar_trials = np.load(os.path.join(folder, 'exemplar_trials.npy'))

In [74]:
results.mean(axis=2)

array([[ 0.3315,  0.4224,  0.4416,  0.5025,  0.4401],
       [ 0.6147,  0.6929,  0.6906,  0.6964,  0.6941],
       [ 0.7735,  0.8178,  0.8097,  0.8454,  0.7791],
       [ 0.7488,  0.8401,  0.8469,  0.8578,  0.8783],
       [ 0.7674,  0.7892,  0.853 ,  0.8812,  0.8973],
       [ 0.7613,  0.8831,  0.8588,  0.877 ,  0.9063]])

# First order results

In [75]:
folder = '/Users/reubenfeinman/Desktop/cnn_results_firstOrder/'
results_gen = np.load(os.path.join(folder, 'results_gen.npy'))
results_acc = np.load(os.path.join(folder, 'results_acc.npy'))
category_trials = np.load(os.path.join(folder, 'category_trials.npy'))
exemplar_trials = np.load(os.path.join(folder, 'exemplar_trials.npy'))

In [76]:
results_gen

array([[[ 0.7615,  0.693 ,  0.7885,  0.8015,  0.8065],
        [ 0.8305,  0.804 ,  0.809 ,  0.815 ,  0.7315],
        [ 0.8615,  0.833 ,  0.7975,  0.791 ,  0.8115],
        [ 0.8885,  0.8995,  0.81  ,  0.8595,  0.8675],
        [ 0.845 ,  0.8175,  0.765 ,  0.8945,  0.797 ]],

       [[ 0.876 ,  0.8775,  0.8355,  0.91  ,  0.9225],
        [ 0.883 ,  0.946 ,  0.885 ,  0.948 ,  0.949 ],
        [ 0.956 ,  0.956 ,  0.9415,  0.964 ,  0.966 ],
        [ 0.95  ,  0.964 ,  0.944 ,  0.952 ,  0.9515],
        [ 0.965 ,  0.926 ,  0.9465,  0.901 ,  0.928 ]],

       [[ 0.8595,  0.83  ,  0.859 ,  0.8435,  0.8445],
        [ 0.923 ,  0.8745,  0.9035,  0.9025,  0.892 ],
        [ 0.921 ,  0.8705,  0.904 ,  0.9285,  0.9105],
        [ 0.9325,  0.93  ,  0.916 ,  0.9225,  0.9305],
        [ 0.9335,  0.936 ,  0.9225,  0.9415,  0.941 ]],

       [[ 0.897 ,  0.8535,  0.8625,  0.899 ,  0.8675],
        [ 0.925 ,  0.937 ,  0.946 ,  0.9135,  0.89  ],
        [ 0.9395,  0.9425,  0.948 ,  0.946 ,  0.9535],
    

In [78]:
results_gen.mean(axis=2)

array([[ 0.7702,  0.798 ,  0.8189,  0.865 ,  0.8238],
       [ 0.8843,  0.9222,  0.9567,  0.9523,  0.9333],
       [ 0.8473,  0.8991,  0.9069,  0.9263,  0.9349],
       [ 0.8759,  0.9223,  0.9459,  0.9245,  0.9563],
       [ 0.811 ,  0.8998,  0.9255,  0.942 ,  0.9206],
       [ 0.8637,  0.9272,  0.9325,  0.9343,  0.9206]])

# Combined

In [3]:
folder = '/Users/reubenfeinman/Desktop/cnn_results_combined/'
results_o1_gen = np.load(os.path.join(folder, 'results_o1_gen.npy'))
results_o1_acc = np.load(os.path.join(folder, 'results_o1_acc.npy'))
results_o2_gen = np.load(os.path.join(folder, 'results_o2_gen.npy'))
category_trials = np.load(os.path.join(folder, 'category_trials.npy'))
exemplar_trials = np.load(os.path.join(folder, 'exemplar_trials.npy'))
print('categories: ', category_trials)
print('exemplars: ', exemplar_trials)

categories:  [ 3  6  9 12 15 18]
exemplars:  [ 2  4  8 16 32 50]


In [4]:
results_o1_gen.mean(axis=2)

array([[ 0.3222,  0.4866,  0.7136,  0.8626,  0.8771,  0.7858],
       [ 0.3297,  0.4999,  0.6431,  0.787 ,  0.7635,  0.8182],
       [ 0.3112,  0.5354,  0.7797,  0.8346,  0.8943,  0.8951],
       [ 0.1977,  0.4906,  0.8028,  0.9097,  0.9304,  0.9303],
       [ 0.2148,  0.4843,  0.8447,  0.914 ,  0.9386,  0.961 ],
       [ 0.1265,  0.5079,  0.7373,  0.897 ,  0.9214,  0.9433]])

In [5]:
results_o1_acc.mean(axis=2)

array([[ 0.6364,  0.9087,  0.9747,  0.9957,  0.9924,  0.8516],
       [ 0.4399,  0.6664,  0.7843,  0.8962,  0.8082,  0.8853],
       [ 0.4566,  0.7309,  0.8748,  0.8985,  0.9357,  0.9418],
       [ 0.335 ,  0.6331,  0.9009,  0.9735,  0.9885,  0.9907],
       [ 0.4368,  0.7305,  0.9562,  0.9855,  0.9846,  0.9996],
       [ 0.2006,  0.5518,  0.7927,  0.9341,  0.9845,  0.9923]])

In [6]:
results_o2_gen.mean(axis=2)

array([[ 0.2203,  0.364 ,  0.5804,  0.7035,  0.7182,  0.6259],
       [ 0.1538,  0.2762,  0.3696,  0.4659,  0.4326,  0.4293],
       [ 0.1813,  0.3568,  0.5579,  0.619 ,  0.7022,  0.6961],
       [ 0.1273,  0.3809,  0.6922,  0.8484,  0.8303,  0.8209],
       [ 0.1408,  0.3998,  0.7842,  0.8011,  0.8323,  0.8952],
       [ 0.11  ,  0.3978,  0.6449,  0.7849,  0.857 ,  0.8833]])

# Try smaller model (CNN5)

In [16]:
folder = '../results/cnn_results_combined/'
results_o1_gen = np.load(os.path.join(folder, 'results_o1_gen.npy'))
results_o1_acc = np.load(os.path.join(folder, 'results_o1_acc.npy'))
results_o2_gen = np.load(os.path.join(folder, 'results_o2_gen.npy'))
category_trials = np.load(os.path.join(folder, 'category_trials.npy'))
exemplar_trials = np.load(os.path.join(folder, 'exemplar_trials.npy'))
print('category trials: ', category_trials)
print('exemplar trials: ', exemplar_trials)

category trials:  [ 2  4  8 16 32 50]
exemplar trials:  [ 3  6  9 12 15 18]


In [17]:
get_df(results_o1_gen.mean(axis=2), category_trials, exemplar_trials)

2        4        8        16       32       50
3   0.58355  0.61275   0.7473  0.59785   0.7554  0.76015
6    0.6249  0.80675  0.92635  0.82655   0.8938  0.92945
9    0.6733   0.8528   0.9488   0.8566  0.95605  0.97285
12  0.67845   0.8757  0.95645  0.87545  0.96735  0.98275
15   0.6883  0.87955  0.96035   0.9447  0.97365  0.98575
18   0.7082   0.9244   0.9804  0.93035   0.9811  0.98325

In [18]:
get_df(results_o2_gen.mean(axis=2), category_trials, exemplar_trials)

2        4        8        16       32       50
3   0.32125   0.5174   0.5602  0.42435   0.7126   0.7179
6    0.3204  0.66855  0.73925  0.67745  0.83525  0.91285
9   0.31875   0.7409   0.7574   0.7167  0.90635   0.9488
12   0.3151   0.7263   0.7753  0.73195  0.93145    0.956
15  0.32045    0.725  0.81545   0.8703   0.9543  0.96375
18  0.30705   0.7831  0.82365  0.83465   0.9513  0.96555

# Smaller model, SGD

In [7]:
folder = '../results/cnn_results_combined_sgd/'
results_o1_gen = np.load(os.path.join(folder, 'results_o1_gen.npy'))
results_o1_acc = np.load(os.path.join(folder, 'results_o1_acc.npy'))
results_o2_gen = np.load(os.path.join(folder, 'results_o2_gen.npy'))
category_trials = np.load(os.path.join(folder, 'category_trials.npy'))
exemplar_trials = np.load(os.path.join(folder, 'exemplar_trials.npy'))
print('categories: ', category_trials)
print('exemplars: ', exemplar_trials)

categories:  [ 2  4  8 16 32 50]
exemplars:  [ 3  6  9 12 15 18]


In [8]:
get_df(results_o1_gen.mean(axis=2), category_trials, exemplar_trials)

2        4        8        16       32       50
3   0.55395  0.71015   0.7903  0.64445    0.732  0.77125
6    0.6729   0.8586  0.93535  0.81975  0.91895   0.9371
9    0.6811  0.87455  0.94625  0.91205  0.95375  0.96545
12   0.6464   0.9187   0.9726   0.9253  0.97315  0.98785
15  0.69515   0.9069  0.96755  0.93845   0.9831  0.98605
18   0.7245  0.92605  0.98035   0.9493  0.98395   0.9824

In [9]:
get_df(results_o2_gen.mean(axis=2), category_trials, exemplar_trials)

2        4        8        16       32       50
3   0.30515   0.6084   0.5928   0.4752  0.69755  0.71625
6   0.29635  0.72575   0.7564   0.6771  0.87785   0.9254
9   0.27765  0.75425  0.75215   0.8141  0.93065  0.93795
12    0.285  0.79875  0.78255  0.85095    0.938    0.968
15  0.30505  0.77155  0.80585    0.864   0.9443  0.97155
18  0.29675   0.7829     0.81   0.8712  0.95775  0.97595

In [10]:
get_df(results_o2_gen.std(axis=2), category_trials, exemplar_trials)

2          4          8          16         32          50
3   0.0309662  0.0593004  0.0850671   0.107753  0.0562994    0.042479
6   0.0296142  0.0483137  0.0392866  0.0676523  0.0165409   0.0174439
9   0.0169574  0.0319267  0.0589877  0.0525485  0.0162004     0.02135
12  0.0332821  0.0434777  0.0523615  0.0703649  0.0126056   0.0128511
15  0.0298466  0.0229777  0.0583001  0.0641027  0.0168244  0.00759753
18  0.0246691  0.0307366  0.0416035  0.0519785  0.0122765   0.0105982

# Try one more thing with CNN... randomly selected different shapes, colors and textures to use for training at each run

In [3]:
folder = '../results/cnn_results_combined1/'
results_o1_gen = np.load(os.path.join(folder, 'results_o1_gen.npy'))
results_o2_gen = np.load(os.path.join(folder, 'results_o2_gen.npy'))
category_trials = np.load(os.path.join(folder, 'category_trials.npy'))
exemplar_trials = np.load(os.path.join(folder, 'exemplar_trials.npy'))
print('categories: ', category_trials)
print('exemplars: ', exemplar_trials)

categories:  [ 2  4  8 16 32 50]
exemplars:  [ 3  6  9 12 15 18]


In [4]:
get_df(results_o1_gen.mean(axis=2), category_trials, exemplar_trials)

2       4       8       16      32      50
3   0.5631  0.6555  0.7513  0.7702  0.7896  0.7723
6   0.6208  0.8397  0.8881  0.9181  0.9312  0.9448
9   0.6676  0.8438  0.9267  0.9533  0.9586  0.9602
12  0.6951  0.9084  0.9454  0.9729  0.9733       0
15  0.6826  0.9081  0.9598  0.9809  0.9797       0
18  0.7258  0.9179   0.956   0.984  0.9814       0

In [5]:
get_df(results_o2_gen.mean(axis=2), category_trials, exemplar_trials)

2       4       8       16      32      50
3   0.3884  0.5161  0.5933  0.6586  0.7395  0.7525
6   0.4351  0.6422   0.749  0.7968  0.8986  0.9181
9   0.4298  0.6367  0.8116  0.8781   0.906  0.9429
12  0.4647  0.6983  0.8214  0.9128  0.9296       0
15  0.4344  0.6809  0.8591  0.9103   0.952       0
18  0.4725  0.7618  0.8328  0.8979  0.9449       0

In [39]:
get_df(results_o2_gen.std(axis=2), category_trials, exemplar_trials)

2          4  8  16 32 50
3    0.138255   0.153768  0  0  0  0
6    0.112055   0.126038  0  0  0  0
9     0.11662   0.121838  0  0  0  0
12   0.145925  0.0786156  0  0  0  0
15  0.0927795   0.104557  0  0  0  0
18   0.106079          0  0  0  0  0

# MLP results

In [122]:
folder = '../results/mlp_results_combined/'
results_o1_gen = np.load(os.path.join(folder, 'results_o1_gen.npy'))
results_o2_gen = np.load(os.path.join(folder, 'results_o2_gen.npy'))
category_trials = np.load(os.path.join(folder, 'category_trials.npy'))
exemplar_trials = np.load(os.path.join(folder, 'exemplar_trials.npy'))
print('categories: ', category_trials)
print('exemplars: ', exemplar_trials)

categories:  [ 2  4  8 16 32 50]
exemplars:  [ 3  6  9 12 15 18]


In [123]:
get_df(results_o1_gen.mean(axis=2), category_trials, exemplar_trials)

2       4       8       16      32      50
3    0.862  0.8659  0.7762  0.8436  0.7809  0.7907
6   0.8719  0.9724  0.9577  0.9204  0.9847   0.993
9   0.8577   0.967  0.9801   0.982  0.9991  0.9999
12  0.8753  0.9803  0.9814  0.9929  0.9988  0.9996
15  0.8431  0.9712  0.9838   0.998  0.9992  0.9997
18  0.8699  0.9913  0.9961  0.9999  0.9998  0.9988

In [124]:
get_df(results_o2_gen.mean(axis=2), category_trials, exemplar_trials)

2       4       8       16      32      50
3   0.5905  0.6482  0.5205  0.7925  0.7146  0.7926
6   0.6127  0.7834  0.7949  0.8489  0.9762  0.9888
9   0.6233  0.7947  0.8611  0.9793  0.9992       1
12  0.5987  0.8422  0.8468  0.9775       1       1
15  0.5859  0.8153  0.8824  0.9993       1       1
18  0.6051  0.8733  0.9275       1       1       1

In [22]:
# MLP with noise=10%

folder = '../results/mlp_results_combined_n10/'
results_o1_gen = np.load(os.path.join(folder, 'results_o1_gen.npy'))
results_o2_gen = np.load(os.path.join(folder, 'results_o2_gen.npy'))
category_trials = np.load(os.path.join(folder, 'category_trials.npy'))
exemplar_trials = np.load(os.path.join(folder, 'exemplar_trials.npy'))
print('categories: ', category_trials)
print('exemplars: ', exemplar_trials)

categories:  [ 2  4  8 16 32 50]
exemplars:  [ 3  6  9 12 15 18]


In [23]:
get_df(results_o1_gen.mean(axis=2), category_trials, exemplar_trials)

2       4       8       16 32 50
3   0.6652  0.7395  0.6622  0.7398  0  0
6   0.7436  0.8357  0.8242   0.855  0  0
9   0.7359  0.8611   0.864       0  0  0
12  0.7636  0.8743  0.8762       0  0  0
15  0.7554  0.8947  0.8945       0  0  0
18  0.7687  0.8883  0.8935       0  0  0

In [24]:
get_df(results_o2_gen.mean(axis=2), category_trials, exemplar_trials)

2       4       8       16 32 50
3   0.4231  0.5192  0.4491  0.6619  0  0
6   0.4748  0.5996  0.6256  0.7721  0  0
9   0.4716  0.6076  0.6877       0  0  0
12  0.4691  0.5935  0.7021       0  0  0
15  0.4748  0.6447  0.7099       0  0  0
18  0.4866  0.6382  0.7519       0  0  0